### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by Michael-S** [yosbelms/ramdascript#2]
I think it would be useful for anyone that wants to look at this code and play with it for you to add a license file.  Ramda.js itself is under the MIT License https://github.com/ramda/ramda/blob/master/LICENSE.txt  so that's an option to consider - but it's your choice, of course.

**Comment by yosbelms** [comment]
RamdaScript is MIT licensed from the beginning. It has a license file now, https://github.com/yosbelms/ramdascript/blob/master/LICENSE

**Comment by Michael-S** [comment]
Thank you!
