### ISSUE TITLE
Add let

### ISSUE THREAD

**Issue by rockymadden** [yosbelms/ramdascript#5]
Perhaps there is a way to accomplish this already that I am not seeing?

**Comment by yosbelms** [comment]
@rockymadden , I was recently thinking about it because right now there is no way to declare local variables in RamdaScript.

An alternative to `let` could be to allow to use `def` inside a function, example:
```
(def someFn (fn []
    // using def locally
    (def internalVar nil)
    (callAFunc internalVar)))
```

**Comment by rockymadden** [comment]
@yosbelms Nice! I swore I tried that, but perhaps overlooked something when I did it. Thought of also `useWith` for this use case as well, prepping everything in transformer functions (one per variable) and then having those all passed to the "main" function as arguments.

**Comment by yosbelms** [comment]
@rockymadden my proposal is added in 982fbd61a425e57efddbad446f5f9ec71ffeaf1d will be included in the next release along with a regex fix and some improvements to the playground

**Comment by yosbelms** [comment]
@rockymadden Merged and released, see example of usage [here](https://yosbelms.github.io/ramdascript/#link:%0A(def%20someFn%20(fn%20%5B%5D%0A%20%20%20%20(def%20num1%201)%0A%20%20%20%20(def%20num2%202)%0A%20%20%20%20(sum%20num1%20num2))))

**Comment by rockymadden** [comment]
Fantastic, thank you!
