### ISSUE TITLE
Compiled Ramdascript does not import the Ramda library

### ISSUE THREAD

**Issue by MarcCoquand** [yosbelms/ramdascript#8]
When I tried to compile Ramdascript to javascript with the following command:
`ram compile -src server/server.ram -format none`

It compiled without error however when trying to run the file it throws an error that R is not defined. This is due to the fact that the compiled file never imports the ramda library. A workaround for now is to manually add the line 'R = require('ramda') at the top of each compiled file but it's not ideal.

**Comment by yosbelms** [comment]
Try:
```sh
ram compile -src server/server.ram -format cjs
```
or just
```sh
ram compile -src server/server.ram
```

The `-format` CLI option specifies the module format of the resulting JS. As of you provide `none` the compiler does not add the `require`s to the header, because it is a specific for __CommonJS__ idiom. So, you can either provide `-format cjs` or leave it without specify -in this case RamdaScript will use CommonJS (cjs) as default-

**Comment by MarcCoquand** [comment]
Okay I tried to compile it using `-format cjs` but it yields the error

```
/usr/local/lib/node_modules/ramdascript/src/compiler.js:385
    Object.keys(ctx.definedVars).forEach(function(name, idx, arr){
           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at writeCommonJSStub (/usr/local/lib/node_modules/ramdascript/src/compiler.js:385:12)
    at Object.astToChunks (/usr/local/lib/node_modules/ramdascript/src/compiler.js:423:13)
    at srcToChunks (/usr/local/lib/node_modules/ramdascript/src/ramdascript.js:53:25)
    at Object.compile (/usr/local/lib/node_modules/ramdascript/src/ramdascript.js:23:18)
    at /usr/local/lib/node_modules/ramdascript/src/cli.js:202:26
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

but it compiles with `-format none`. This was tested with a file that just contains `(console.log 'hello')`

**Comment by yosbelms** [comment]
Nice catch! let me know if this works for you

**Comment by MarcCoquand** [comment]
Tested it and it works now. Thanks, this is a fantastic project.
